services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mongo
      MONGO_URI: "mongodb+srv://ivanbilotserkivskiy:NinWAYG6wSu2p2aK@cluster0.oslcqu1.mongodb.net/?retryWrites=true&w=majority"
      
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
      PORT: 3000
      JWT_SECRET: WirPObXGw8mXnNq3LTCKciwSr44oUUx2Nd9aViBGpawmibXXoHSmxzlCKvNCsqli
      DB_URL: mongodb+srv://ivanbilotserkivskiy:NinWAYG6wSu2p2aK@cluster0.oslcqu1.mongodb.net/?retryWrites=true&w=majority

    depends_on:
      - mongodb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge