services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_HOST: mysql-bbcb407-torentino56-d5ca.aivencloud.com
      MYSQL_USER: avnadmin
      MYSQL_PASSWORD: VNS_iVj1dhVmNOIkEG33Bc0
      MYSQL_ROOT_PASSWORD: VNS_iVj1dhVmNOIkEG33Bc0
      SERVICE_TAGS: dev
      SERVICE_NAME: defaultdb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 3001:3001
      - 8001:8001
    expose:
      - 3001
      - 8001
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
      PORT: 3001
      WS_PORT: 8001
      DB_PORT: 20352
      DB_NAME: defaultdb
      DB_USER: 'avnadmin'
      DB_HOST: 'mysql-bbcb407-torentino56-d5ca.aivencloud.com'
      DB_PASSWORD: 'AVNS_iVj1dhVmNOIkEG33Bc0'
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge